# Generated by Django 2.1.7 on 2019-04-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_album_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
