# Generated by Django 2.1.7 on 2019-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_remove_song_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='Black-square.jpg', upload_to='album_logo'),
        ),
    ]
