# Generated by Django 2.1.7 on 2019-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20190407_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='logo.jpg', upload_to='album_logo'),
        ),
    ]
