# Generated by Django 2.1.7 on 2019-04-13 16:51

from django.db import migrations, models
import songs.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20190411_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(default='amber_treble.png', upload_to='album_logo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=songs.formatChecker.ContentTypeRestrictedFileField(upload_to='audio_files/'),
        ),
    ]
